server:
  port: 8081


spring:
  profiles:
    active:
    - prod
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
